Repository UBC-MDS/picturepyfect, pull requests merged in 2021-03, with the labels that each got.

#27 Image property feature function implementation and tests
  img/black.png
  img/blue.png
  img/green.png
  img/red.png
  img/white.png
  picturepyfect/get_property.py
  picturepyfect/picturepyfect.py
  poetry
  pyproject.toml
  tests/test_get_property.py
  tests/test_picturepyfect.py
Labels: code

#33 Rotation pyfect
  picturepyfect/rotate_pyfect.py
  tests/test_rotation_pyfect.py
Labels: code, documentation

#36 Rotation pyfect
  picturepyfect/rotate_pyfect.py
  tests/test_rotation_pyfect.py
Labels: bug, enhancement

#38 Add import for rotation function
  picturepyfect/compression_pyfect.py
  tests/test_compression_pyfect.py
Labels: bug, code
